local-phone-apps = AccessoryKeyDispatcher \
                   AdobeFlashPlayer \
                   ApplicationsProvider \
                   AudioEffectService \
                   Bluetooth \
                   bootinfo \
                   CameraExtensionPermission \
		   CdfInfoAccessor   \
                   CertInstaller \
                   CredentialManagerService \
                   DefaultCapabilities \
                   DefaultContainerService \
                   enhancedusbux \
		   ES_File_Explorer \
                   FaceLock \
                   GenericApplicationInstaller \
                   Initial-boot-setup \
                   livewallpaperearth \
		   InfiniteView  \
                   MediaProvider \
                   MemcardTransportService \
                   Nfc \
                   PackageInstaller \
                   qcsemcservice \
                   Radio3 \
                   SemcCamera3D \
		   QuickPanelSettings  \
		   SecWallpaperChooser  \
		   SemcAlbum  \
		   SemcAutoPowerOff  \
                   SemcCameraUI \
		   SemcClock  \
                   ServiceMenu \
                   SoundEnhancement \
                   usb-mtp-backup-transport \
                   usb-mtp-marlin-wrapper \
                   usb-mtp-update-wrapper \
                   usb-mtp-vendor-extension-service \
                   usbotg \
                   UsbTransportService \
                   UserDictionaryProvider \
		   UxpNxtLockScreen  \
                   WapiCustomization \
                   WapPush \
		   WeatherWidget  \
		   Youtube
